apiVersion: autotune.mikeziminio.github.io/v1alpha1
kind: QueueScalingPolicy
metadata:
  labels:
    app.kubernetes.io/name: queue-autotunner
    app.kubernetes.io/managed-by: kustomize
  name: queuescalingpolicy-sample
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  rabbitmq:
    queue: orders
  scaling:
    minReplicas: 1
    maxReplicas: 5
