apiVersion: autotune.mikeziminio.github.io/v1alpha1
kind: QueueScalingPolicy
metadata:
  labels:
    app.kubernetes.io/name: queue-autotunner
    app.kubernetes.io/managed-by: kustomize
  name: queuescalingpolicy-sample
spec:
  # TODO(user): Add fields here
